# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baserepo: "https://github.com/leaningtech"
url: "https://docs.leaningtech.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "docs.leaningtech.com"

email: info@leaningtech.com
social_links:
  twitter: leaningtech
  github:  leaningtech
  medium:  leaningtech
  linkedin: leaning-technologies-Ltd

# Build settings
markdown: kramdown

plugins:
 - jekyll-seo-tag

blog: "https://leaningtech.com/news/?technicalblog"

defaults:
  - scope:
      path: ""
    values:
      image: "https://opengraph.githubassets.com/19821c25899861c60f24bbabafd28c924982e74a2edb07a58a3d28f6f5210efb/leaningtech/leaningtech.github.io"
      section-title: Leaning Technologies Documentation
      logo: "/assets/leaningtech.jpg"
      baseurl: "/"
      baseurl_no: ""
      tagline:
        line1: "Leaning Technologies Documentation"
        line2: "Developer oriented knowledge"
      header_selection:
        website: https://leaningtech.com/                          # Change to relevant website (eg. product one)
        #repository: https://github.com/leaningtech/leaningtech-docs    # Change to relevant repo
        #issues: https://github.com/leaningtech/leaningtech-docs/issues # Change here
        #chat: https://gitter.im/leaningtech/cheerp                 # Change here
        blog: "https://leaningtech.com/news/?technicalblog"
        contactus: https://leaningtech.com/contact-us/
        #general_about: "/about"
      source_repo: "https://github.com/leaningtech/leaningtech.github.io/"
      description: >- # this means to ignore newlines until "something:"
        Documentation for Cheerp, CheerpJ, CheerpJ Applet Runner and CheerpX For Flash
      index: index.html
      index-specific: index-specific.html
  - scope:
      path: "README.md"
    values:
      permalink: "/"
  - scope:
      path: "cheerp"
    values:
      is_product: 1
      image: "https://opengraph.githubassets.com/19821c25899861c60f24bbabafd28c924982e74a2edb07a58a3d28f6f5210efb/leaningtech/cheerp-meta"
      section-title: Cheerp Documentation
      logo: "/assets/cheerp_logo.png"
      baseurl: "/cheerp/"
      baseurl_no: "cheerp/"
      tagline:
        line1: "Cheerp | the C++ compiler for the Web"
        line2: "Documentation & Tutorials"
      header_selection:
        website: https://leaningtech.com/cheerp/
        repository: https://github.com/leaningtech/cheerp-meta    # Change to relevant repo
        issues: https://github.com/leaningtech/cheerp-meta/issues # Change here
        chat: https://gitter.im/leaningtech/cheerp                 # Change here
        contactus: https://leaningtech.com/contact-us/?subject=Cheerp%20Information%20Request#mailus
      download: "https://leaningtech.com/cheerp/#download"
      source_repo: "https://github.com/leaningtech/cheerp-meta/"
      description: >- # this means to ignore newlines until "something:"
        Cheerp is the enterprise-grade C/C++ compiler for the Web and can compile C/C++ into WebAssembly and JavaScript.
      index: cheerp/index.html
      index-specific: cheerp/index-specific.html
  - scope:
      path: "cheerp/README.md"
    values:
      permalink: "/cheerp/"
  - scope:
      path: "cheerpj-applet-runner"
    values:
      is_product: 1
      image: "https://opengraph.githubassets.com/19821c25899861c60f24bbabafd28c924982e74a2edb07a58a3d28f6f5210efb/leaningtech/cheerpj-appletrunner"
      section-title: CheerpJ Applet Runner Documentation
      logo: "/assets/cheerpj_logo.png"
      baseurl: "/cheerpj-applet-runner/"
      baseurl_no: "cheerpj-applet-runner/"
      tagline:
        line1: "CheerpJ Applet Runner"
        line2: "Documentation & Tutorials"
      header_selection:
        website: https://leaningtech.com/cheerpj-applet-runner/
        # repository: https://github.com/leaningtech/cheerpj-appletrunner    # Change to relevant repo
        issues: https://github.com/leaningtech/cheerpj-appletrunner/issues # Change here
        chat: https://gitter.im/leaningtech/cheerpj                # Change here
        contactus: https://leaningtech.com/contact-us/?subject=CheerpJ%20Applet%20Runner%20Information%20Request#mailus
        #about: "/cheerp/about"
      index-links:
        #download: "https://leaningtech.com/cheerp/#download"
        chrome: "https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein"
        edge: "https://microsoftedge.microsoft.com/addons/detail/cheerpj-applet-runner/ebfcpaoldmijengghefpohddmfpndmic"
        privacy: "https://leaningtech.com/privacy-policy-cheerpj-ar/"
      source_repo: "https://github.com/leaningtech/cheerpj-appletrunner/"
      description: >- # this means to ignore newlines until "something:"
        CheerpJ Applet Runners allowing you to convert on-the-fly any Java client application into standard HTML5, WebAssembly or JavaScript.
      index: cheerpj-applet-runner/index.html
      index-specific: cheerpj-applet-runner/index-specific.html
  - scope:
      path: "cheerpj-applet-runner/README.md"
    values:
      permalink: "/cheerpj-applet-runner/"
  - scope:
      path: "cheerpj"
    values:
      is_product: 1
      image: "https://opengraph.githubassets.com/19821c25899861c60f24bbabafd28c924982e74a2edb07a58a3d28f6f5210efb/leaningtech/cheerpj-meta"
      section-title: CheerpJ Applet Runner Documentation
      logo: "/assets/cheerpj_logo.png"
      baseurl: "/cheerpj/"
      baseurl_no: "cheerpj/"
      tagline:
        line1: "CheerpJ | the Java solution for the Web"
        line2: "Documentation & Tutorials"
      header_selection:
        website: https://leaningtech.com/cheerpj/
        # repository: https://github.com/leaningtech/cheerpj-appletrunner    # Change to relevant repo
        issues: https://github.com/leaningtech/cheerpj-meta/issues # Change here
        chat: https://gitter.im/leaningtech/cheerpj                # Change here
        contactus: https://leaningtech.com/contact-us/?subject=CheerpJ%20Information%20Request#mailus
        #about: "/cheerp/about"
      index-links:
        download: "https://leaningtech.com/download-cheerpj/"
        licence: "https://leaningtech.com/cheerpj-licensing/"
        demo: "https://leaningtech.com/demo/?cheerpjfilter"
        #privacy: "https://leaningtech.com/privacy-policy-cheerpj-ar/"
      source_repo: "https://github.com/leaningtech/cheerpj-appletrunner/"
      description: >- # this means to ignore newlines until "something:"
        CheerpJ is the java compiler for the Web, allowing you to convert any Java client application into standard HTML5, WebAssembly or JavaScript.
      index: cheerpj/index.html
      index-specific: cheerpj/index-specific.html
  - scope:
      path: "cheerpj/README.md"
    values:
      permalink: "/cheerpj/"
  - scope:
      path: "cheerpx-for-flash"
    values:
      is_product: 1
      image: "https://opengraph.githubassets.com/19821c25899861c60f24bbabafd28c924982e74a2edb07a58a3d28f6f5210efb/leaningtech/cheerpx-flash"
      section-title: CheerpX For Flash Documentation
      logo: "/assets/cheerpx_logo.png"
      baseurl: "/cheerpx-for-flash/"
      baseurl_no: "cheerpx-for-flash/"
      tagline:
        line1: "CheerpX For Flash | Flash for the modern Web"
        line2: "Documentation & Tutorials"
      header_selection:
        website: https://leaningtech.com/cheerpx-for-flash/
        # repository: https://github.com/leaningtech/cheerpj-appletrunner    # Change to relevant repo
        #issues: https://github.com/leaningtech/cheerpj-meta/issues # Change here
        #chat: https://gitter.im/leaningtech/cheerpj                # Change here
        contactus: https://leaningtech.com/contact-us/?subject=CheerpX%20For%20Flash%20Information%20Request#mailus
        #about: "/cheerp/about"
      index-links:
        download: "https://leaningtech.com/download-cheerpx-for-flash/"
        licence: "https://leaningtech.com/cheerpx-for-flash-licensing/"
        demo: "https://leaningtech.com/demo/?cheerpxfilter"
        book_demo: "https://leaningtech.com/cheerpx-for-flash/#contact"
      source_repo: "https://github.com/leaningtech/cheerpx-flash/"
      description: >- # this means to ignore newlines until "something:"
        Main documentation and tutorials for CheerpX For Flash | run Flash content in the browser without the Flash Player.
      index: cheerpx-for-flash/index.html
      index-specific: cheerpx-for-flash/index-specific.html
  - scope:
      path: "cheerpx-for-flash/README.md"
    values:
      permalink: "/cheerpx-for-flash/"

docs_repo: "https://github.com/leaningtech/leaningtech.github.io/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
